version: "2.1"
services:

  project-app:
    image: tomcat:jdk8
    container_name: project-app
    restart: on-failure:3
    volumes:
      - ./docker/data/logs/tomcat:/usr/local/tomcat/logs
      - ./out/artifacts/hotel/:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n

  project-mysql:
    container_name: project-mysql
    image: cytopia/mysql-5.6
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hotel
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  project-redis:
    image: redis:3.0
    container_name: project-redis
    restart: on-failure:3
    volumes:
      - ./docker/data/redis:/data
    ports:
      - "6379:6379"